### ISSUE TITLE
add Windows support

### ISSUE THREAD

**Issue by agentm** [solidsnack/wcwidth#2]
If I post a pull request to add Windows support, is there any chance the package will be updated? 

Considering that the package has not been updated in years, I am trying to gauge the liveliness of this module.

**Comment by solidsnack** [comment]
Yes, it will be updated.

**Comment by simonmichael** [comment]
Ping.. we just discovered this package, and would use windows support.

**Comment by agentm** [comment]
I ended up porting C source to a [pure Haskell implementation](https://github.com/agentm/project-m36/blob/master/src/lib/ProjectM36/WCWidth.hs).

**Comment by solidsnack** [comment]
Sorry, not paying attention.

**Comment by simonmichael** [comment]
Thanks!

I'll watch for a release. master builds for me on mac using stack or cabal, but I feel like there might be something wrong:
```
~/src/DEVTOOLS/wcwidth$ cabal install
Warning: The install command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-install
command or the legacy v1-install alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Resolving dependencies...
Downloading  rset-1.0.0
Downloaded   rset-1.0.0
Starting     rset-1.0.0
Building     rset-1.0.0
Completed    rset-1.0.0
Starting     wcwidth-0.0.2
Building     wcwidth-0.0.2
Completed    wcwidth-0.0.2
~/src/DEVTOOLS/wcwidth$ ghc-pkg list wcwidth
WARNING: there are broken packages.  Run 'ghc-pkg check' for more details.
/usr/local/Cellar/ghc/8.2.2/lib/ghc-8.2.2/package.conf.d
    (no packages)
/Users/simon/.ghc/x86_64-darwin-8.2.2/package.conf.d
    wcwidth-0.0.2
~/src/DEVTOOLS/wcwidth$ ghci
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /Users/simon/.ghci
Prelude> import Data.Char.WCWidth

<interactive>:1:1: error:
    attempting to use module ‘main:Data.Char.WCWidth’ (./Data/Char/WCWidth.hs) which is not loaded
```

**Comment by simonmichael** [comment]
@solidsnack ping.. would you be willing to do a hackage release, eg to help https://github.com/simonmichael/hledger/issues/895 ? Last release was in 2011. Or if not, find a new maintainer - I think you'll have more luck on haskell-cafe or #haskell ?

**Comment by solidsnack** [comment]
The request went out today: https://mail.haskell.org/pipermail/haskell-cafe/2019-July/131353.html
